#APPLICATION
spring.application.name=agenda
spring.profiles.active=local

#DATABASE CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5432/agenda_db

#JPA / HIBERNATE CONFIGS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true